<a href="https://colab.research.google.com/github/pranukrish/CMPE255_DataMining/blob/main/Assignment4/Question2/AutoViML_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This Collab is to demonstrate the auto ML tools - AutoViML,FeatureViz

#1. autiViML Demo

In [ ]:
### CREATE VIRTUAL DISPLAY ###
!apt-get install -y xvfb # Install X Virtual Frame Buffer
import os
os.system('Xvfb :1 -screen 0 1600x1200x16  &')    # create virtual display with size 1600x1200 and 16 bit color. Color can be changed to 24 or 8
os.environ['DISPLAY']=':1.0'  

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  xvfb
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 785 kB of archives.
After this operation, 2,271 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 xvfb amd64 2:1.19.6-1ubuntu4.11 [785 kB]
Fetched 785 kB in 1s (527 kB/s)
Selecting previously unselected package xvfb.
(Reading database ... 123991 files and directories currently installed.)
Preparing to unpack .../xvfb_2%3a1.19.6-1ubuntu4.11_amd64.deb ...
Unpacking xvfb (2:1.19.6-1ubuntu4.11) ...
Setting up xvfb (2:1.19.6-1ubuntu4.11) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...


In [ ]:
%matplotlib inline

In [ ]:
!pip install --quiet autoVIML

     |████████████████████████████████| 133 kB 4.4 MB/s 
     |████████████████████████████████| 268 kB 41.4 MB/s 
     |████████████████████████████████| 125 kB 67.0 MB/s 
     |████████████████████████████████| 76.6 MB 1.2 MB/s 
     |████████████████████████████████| 255.9 MB 43 kB/s 
     |████████████████████████████████| 240 kB 45.1 MB/s 
     |████████████████████████████████| 569 kB 56.9 MB/s 
     |████████████████████████████████| 11.2 MB 39.9 MB/s 
     |████████████████████████████████| 965 kB 61.9 MB/s 
     |████████████████████████████████| 1.6 MB 42.8 MB/s 
     |████████████████████████████████| 121 kB 58.3 MB/s 
     |████████████████████████████████| 83 kB 2.0 MB/s 


In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
!pip uninstall matplotlib



Found existing installation: matplotlib 3.5.3
Uninstalling matplotlib-3.5.3:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/matplotlib-3.5.3-py3.7-nspkg.pth
    /usr/local/lib/python3.7/dist-packages/matplotlib-3.5.3.dist-info/*
    /usr/local/lib/python3.7/dist-packages/matplotlib/*
    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/axes_grid/*
    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/axes_grid1/*
    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/axisartist/*
    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/mplot3d/*
    /usr/local/lib/python3.7/dist-packages/mpl_toolkits/tests/*
    /usr/local/lib/python3.7/dist-packages/pylab.py
Proceed (y/n)? y
  Successfully uninstalled matplotlib-3.5.3
     |████████████████████████████████| 13.1 MB 26.4 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-ensemble 

In [29]:
!pip install --quiet matplotlib==3.0.2

In [30]:
!pip show matplotlib 

Name: matplotlib
Version: 3.5.3
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/local/lib/python3.7/dist-packages
Requires: pyparsing, pillow, packaging, fonttools, numpy, kiwisolver, cycler, python-dateutil
Required-by: yellowbrick, wordcloud, seaborn, scikit-image, pycocotools, prophet, plotnine, pandas-profiling, mlxtend, mizani, missingno, matplotlib-venn, keras-vis, imgaug, imbalanced-ensemble, fastai, descartes, datascience, daft, catboost, autoviml, arviz


In [ ]:
matplotlib.

In [ ]:
from autoviml.Auto_ViML import Auto_ViML

Imported Auto_ViML version: 0.1.710. Call using:
             m, feats, trainm, testm = Auto_ViML(train, target, test,
                            sample_submission='',
                            scoring_parameter='', KMeans_Featurizer=False,
                            hyper_param='RS',feature_reduction=True,
                             Boosting_Flag='CatBoost', Binning_Flag=False,
                            Add_Poly=0, Stacking_Flag=False,Imbalanced_Flag=False,
                            verbose=1)
            

Imported Auto_NLP version: 0.1.01.. Call using:
     train_nlp, test_nlp, nlp_pipeline, predictions = Auto_NLP(
                nlp_column, train, test, target, score_type='balanced_accuracy',
                modeltype='Classification',top_num_features=200, verbose=0,
                build_model=True)


In [7]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Data/cardio_train.csv", sep = ";")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
sample_submission = ''
scoring_parameter = 'balanced-accuracy'


In [ ]:
#x = df.iloc[:, 0:4].values
#y = df.iloc[:, 4].values

In [ ]:
'''num = int(0.1*df.shape[0])
train = df[:num]
test = df[num: 2*num]
'''

num = int(0.9 *df.shape[0])
train = df[:num]
print(train.shape)
test = df[num:]
print(test.shape)

(35989, 13)
(3999, 13)


In [ ]:
num

35989

In [9]:
target = 'cardio'

In [31]:
m, feats, trainm, testm = Auto_ViML(train, target, test, sample_submission,
                                    scoring_parameter=scoring_parameter,
                                    hyper_param='GS', feature_reduction=True,
                                    Boosting_Flag=True, Binning_Flag=False,
                                    Add_Poly=0, Stacking_Flag=False,
                                    Imbalanced_Flag=False, verbose=1)

##############  D A T A   S E T  A N A L Y S I S  #######################
ALERT! Changing hyperparameter search to RS. Otherwise XGBoost will take too long for 10,000+ rows.
Training Set Shape = (35989, 13)
    Training Set Memory Usage = 3.57 MB
Test Set Shape = (3999, 13)
    Test Set Memory Usage = 0.40 MB
Single_Label Target: ['cardio']

################ Binary_Classification VISUALIZATION Started #####################
Random shuffling the data set before training
    Using RandomizedSearchCV for Hyper Parameter Tuning. This is 3X faster than GridSearchCV...
       Class  -> Counts -> Percent
           0:   18025  ->   50.1%
           1:   17964  ->   49.9%
    Target cardio is already numeric. No transformation done.
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Cl

ImportError: ignored

<Figure size 1080x360 with 1 Axes>

Splitting selected features into float and categorical (integer) variables:
    (1) float variables ...
    (10) categorical vars...
###############################################################################
#######     F E A T U R E   S E L E C T I O N    BY   X G B O O S T    ########
###############################################################################
Current number of predictors = 11 
    Finding Important Features using Boosted Trees algorithm...
        using 11 variables...
        using 9 variables...
        using 7 variables...
        using 5 variables...
        using 3 variables...
Found 10 important features
    Performing limited feature engineering for binning, add_poly and KMeans_Featurizer flags  ...
    Train CV Split completed with TRAIN rows =  28791 , CV rows =  7198
    Binning_Flag set to False or there are no float vars in data set to be binned
    KMeans_Featurizer set to False or there are no float variables in data
Performing MinMax scaling o

ImportError: ignored

<Figure size 432x432 with 1 Axes>

    Using threshold=0.5. However, 0.395 provides better F1=0.74 for rare class...
########################################################
XGBoost Model Prediction Results on Held Out CV Data Set:
    Regular Accuracy Score = 71.9%
Balanced Accuracy = 73.54% with Threshold = 0.50
Confusion Matrix:
[[2847  758]
 [1146 2447]]
              precision    recall  f1-score   support

           0       0.71      0.79      0.75      3605
           1       0.76      0.68      0.72      3593

    accuracy                           0.74      7198
   macro avg       0.74      0.74      0.73      7198
weighted avg       0.74      0.74      0.73      7198

Balanced Accuracy = 71.96% with Threshold = 0.40
Confusion Matrix:
[[2336 1269]
 [ 750 2843]]
              precision    recall  f1-score   support

           0       0.76      0.65      0.70      3605
           1       0.69      0.79      0.74      3593

    accuracy                           0.72      7198
   macro avg       0.72      0.72  

After multiple models, Ensemble Model Results:
Binary Class Model Metrics Report
#####################################################
    Accuracy          = 72.9%
    Balanced Accuracy = 72.9%
    Precision         = 71.8%
    Average Precision = 72.9%
    Recall            = 75.2%
    F1 Score          = 73.5%
#####################################################
              precision    recall  f1-score   support

           0       0.74      0.71      0.72      3605
           1       0.72      0.75      0.73      3593

    accuracy                           0.73      7198
   macro avg       0.73      0.73      0.73      7198
weighted avg       0.73      0.73      0.73      7198

[[2546 1059]
 [ 892 2701]]
#############################################################################
Single Model is better than Ensembling Models for this data set.


ImportError: ignored

<Figure size 720x720 with 1 Axes>

ImportError: ignored

<Figure size 1080x1080 with 6 Axes>

ImportError: ignored

<Figure size 720x360 with 1 Axes>

    Time taken for this Target (in seconds) = 371
    Binning_Flag set to False or there are no float vars in data set to be binned
Performing MinMax scaling of train and test data...
###########################################################################
#####   F I N A L I Z I N G   M O D E L   O N    F U L L   T R A I N  #####
###########################################################################
     Actual Training time taken in seconds = 10
Training of models completed. Now starting predictions on test data...
    Making test Data predictions using modified Threshold = 0.395
    Calculating weighted average ensemble of 5 classifiers
    Plotting Feature Importances to explain the output of model
############### P R E D I C T I O N  O N  T E S T   C O M P L E T E D  #################
    Time taken thus far (in seconds) = 395
Writing Output files to disk...
    Saving predictions to ./cardio/cardio_Binary_Classification_test_modified.csv
    Saving predictions to ./cardio

ImportError: ignored

<Figure size 720x360 with 1 Axes>

#FeatureViz Demo

In [1]:
!pip install --quiet featurewiz

     |████████████████████████████████| 111 kB 4.4 MB/s 
     |████████████████████████████████| 3.2 MB 33.4 MB/s 
     |████████████████████████████████| 2.0 MB 33.6 MB/s 
     |████████████████████████████████| 26.7 MB 1.6 MB/s 
     |████████████████████████████████| 255.9 MB 42 kB/s 
     |████████████████████████████████| 72 kB 771 kB/s 
     |████████████████████████████████| 96 kB 6.6 MB/s 
     |████████████████████████████████| 1.6 MB 50.2 MB/s 
     |████████████████████████████████| 121 kB 54.9 MB/s 
     |████████████████████████████████| 83 kB 2.4 MB/s 


In [14]:
from featurewiz import featurewiz

In [15]:
features = featurewiz(df, target)

############################################################################################
############       F A S T   F E A T U R E  E N G G    A N D    S E L E C T I O N ! ########
# Be judicious with featurewiz. Don't use it to create too many un-interpretable features! #
############################################################################################
Correlation Limit = 0.9
Skipping feature engineering since no feature_engg input...
Skipping category encoding since no category encoders specified in input...
#### Single_Label Binary_Classification problem ####
    Loaded train data. Shape = (39988, 13)
#### Single_Label Binary_Classification problem ####
No test data filename given...
Classifying features using a random sample of 10000 rows from dataset...
#### Single_Label Binary_Classification problem ####
    loading a random sample of 10000 rows into pandas for EDA
#######################################################################################
############

In [16]:
print('Selected %d features:%s' %(len(features),features))

Selected 2 features:(['ap_hi', 'cholesterol', 'ap_lo'],        ap_hi  cholesterol  ap_lo  cardio
0        110            1     80       0
1        140            3     90       1
2        130            3     70       1
3        150            1    100       1
4        100            1     60       0
...      ...          ...    ...     ...
39983    120            1     80       1
39984    120            3     80       1
39985    140            1     80       1
39986    120            1     80       1
39987    140            1    100       1

[39988 rows x 4 columns])
